### ISSUE TITLE
Errors occurred when running MergeSam

### ISSUE THREAD

**Issue by bli25wisc** [erhard-lab/price#1]
Hi @florianerhard ,

I am trying to run gedi's pipeline for Price. I encountered an error when running MergeSam. Any suggestions on fixing it?

Thanks!

My command is 

gedi -e MergeSam -D -t ~/tmp/./parameters/scripts/test.prio.csv -prio ~/tmp/./parameters/scripts/test.prio.oml -chrM -o test.cit

The errors are listed below:

An error occurred: Inappropriate call if not paired read
java.lang.IllegalStateException: Inappropriate call if not paired read
        at htsjdk.samtools.SAMRecord.requireReadPaired(SAMRecord.java:866)
        at htsjdk.samtools.SAMRecord.getSecondOfPairFlag(SAMRecord.java:936)
        at gedi.region.bam.BamAlignedReadDataFactory.addVariations(BamAlignedReadDataFactory.java:331)
        at gedi.region.bam.BamAlignedReadDataFactory.addRecord(BamAlignedReadDataFactory.java:99)
        at gedi.region.bam.FactoryGenomicRegion.add(FactoryGenomicRegion.java:71)
        at gedi.bam.tools.SamToRegion.apply(SamToRegion.java:67)
        at gedi.bam.tools.SamToRegion.apply(SamToRegion.java:38)
        at gedi.util.FunctorUtils$MappedIterator.next(FunctorUtils.java:1110)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:605)
        at gedi.util.FunctorUtils$FilteredIterator.lookAhead(FunctorUtils.java:1059)
        at gedi.util.FunctorUtils$FilteredIterator.hasNext(FunctorUtils.java:1048)
        at gedi.util.FunctorUtils$MergeIterator.insert(FunctorUtils.java:348)
        at gedi.util.FunctorUtils$MergeIterator.next(FunctorUtils.java:323)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:605)
        at gedi.util.FunctorUtils$MappedIterator.hasNext(FunctorUtils.java:1106)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:604)
        at gedi.util.FunctorUtils$FilteredIterator.lookAhead(FunctorUtils.java:1059)
        at gedi.util.FunctorUtils$FilteredIterator.hasNext(FunctorUtils.java:1048)
        at gedi.util.FunctorUtils$InitActionIterator.hasNext(FunctorUtils.java:647)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:604)
        at gedi.util.FunctorUtils$SideEffectIterator.hasNext(FunctorUtils.java:678)
        at gedi.util.FunctorUtils$HasNextActionIterator.hasNext(FunctorUtils.java:767)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:604)
        at gedi.util.FunctorUtils$MultiplexIterator.lookAhead(FunctorUtils.java:950)
        at gedi.util.FunctorUtils$MultiplexIterator.hasNext(FunctorUtils.java:933)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:604)
        at gedi.util.FunctorUtils$MappedIterator.hasNext(FunctorUtils.java:1106)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:604)
        at gedi.util.FunctorUtils$SideEffectIterator.hasNext(FunctorUtils.java:678)
        at gedi.util.FunctorUtils$DemultiplexIterator.lookAhead(FunctorUtils.java:106)
        at gedi.util.FunctorUtils$DemultiplexIterator.hasNext(FunctorUtils.java:90)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:604)
        at gedi.util.FunctorUtils$ResortIterator.tryFillCollector(FunctorUtils.java:1023)
        at gedi.util.FunctorUtils$ResortIterator.hasNext(FunctorUtils.java:998)
        at gedi.util.FunctorUtils$InitActionIterator.hasNext(FunctorUtils.java:647)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:604)
        at gedi.util.FunctorUtils$SideEffectIterator.hasNext(FunctorUtils.java:678)
        at gedi.util.FunctorUtils$HasNextActionIterator.hasNext(FunctorUtils.java:767)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:604)
        at gedi.util.FunctorUtils$MultiplexIterator.lookAhead(FunctorUtils.java:946)
        at gedi.util.FunctorUtils$MultiplexIterator.hasNext(FunctorUtils.java:933)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:604)
        at gedi.util.FunctorUtils$FilteredIterator.lookAhead(FunctorUtils.java:1059)
        at gedi.util.FunctorUtils$FilteredIterator.hasNext(FunctorUtils.java:1048)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:604)
        at gedi.util.FunctorUtils$SideEffectIterator.hasNext(FunctorUtils.java:678)
        at gedi.centeredDiskIntervalTree.CenteredDiskIntervalTreeStorage.fill(CenteredDiskIntervalTreeStorage.java:293)
        at gedi.core.region.GenomicRegionStorage.fill(GenomicRegionStorage.java:182)
        at executables.MergeSam.start(MergeSam.java:295)
        at executables.MergeSam.main(MergeSam.java:84)

**Comment by florianerhard** [comment]
Dear Bo,

you have to give me more details. Could you post the content of the bash script containing the call to MergeSam? Which gedi version did you use?

Best,
Florian

**Comment by bli25wisc** [comment]
@florianerhard , 

Sure thing. I compiled Price 1.0.1 from your source code.

Please see the bash scripts attached.

[test.prio.oml.txt](https://github.com/erhard-lab/price/files/1816664/test.prio.oml.txt)
[test.prio.csv.txt](https://github.com/erhard-lab/price/files/1816671/test.prio.csv.txt)
[test.bash.txt](https://github.com/erhard-lab/price/files/1816672/test.bash.txt)
[start.bash.txt](https://github.com/erhard-lab/price/files/1816673/start.bash.txt)

**Comment by florianerhard** [comment]
Dear Bo,

for using the pipeline, could you use the most recent version from github? We updated htsjdk before 1.0.1 which causes this error. This is fixed in the current version!

Best,
Florian
