### ISSUE TITLE
Error: / by zero

### ISSUE THREAD

**Issue by StevenVerbruggen** [erhard-lab/price#16]
Hi Florian,
Not sure whether you are still actively working on the PRICE tool. But it would be very helpful if I could have some feedback on the following error I occurred. I was running PRICE on a dataset we recently acquired to pinpoint down alternative ORFs. The dataset has around 23 million alignments.
You can find the complete error message below:
```
2022-04-22 12:04:02.007 INFO Command: gedi -e Price -reads /data/steven/OHMX/OHMX20210089_Enara/full_ribo/OHMX20210089_003/STAR/fastq1/price_untreat.bam -genomic homo_sapiens_105 -prefix /data/steven/OHMX/OHMX20210089_Enara/full_ribo/OHMX20210089_003/tmp/PRICE/output -nthreads 1 -fdr 0.1 -D
2022-04-22 12:04:02.294 INFO Discovering classes in classpath
2022-04-22 12:04:02.462 INFO Preparing simple class references
2022-04-22 12:04:02.602 INFO Gedi 1.0.2 (JAR) startup
2022-04-22 12:04:02.838 INFO Reading oml /home/steven/.gedi/genomic/homo_sapiens_105.oml
2022-04-22 12:04:02.849 INFO Done reading oml /home/steven/.gedi/genomic/homo_sapiens_105.oml
2022-04-22 12:04:05.047 INFO Estimating maxpos...
2022-04-22 12:04:05.087 INFO Clustering reads
2022-04-22 12:07:23.765 INFO Found 120555 clusters without looking at annotation
2022-04-22 12:07:25.078 INFO Found 31349 clusters after looking at annotation
2022-04-22 12:07:25.193 INFO Found 15410 clusters after filtering with read/region count
2022-04-22 12:07:27.217 INFO Using maxpos=13 (Merged)
2022-04-22 12:07:27.219 INFO Estimate parameters
2022-04-22 12:32:10.233 INFO LL=-4.84451e+07
2022-04-22 12:32:10.296 INFO Codon inference
2022-04-22 12:38:04.878 INFO Writing codon index
2022-04-22 12:38:04.881 INFO Train start prediction
2022-04-22 12:38:04.880 INFO Calibrate noise model
2022-04-22 12:38:08.780 INFO Writing viewer index
2022-04-22 12:38:13.385 INFO Considering 9798 ORFs for start training
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2699.2
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  12 iterations: 2699.2
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2690.2
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  14 iterations: 2689.6
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2700.3
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  12 iterations: 2700.3
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2683.7
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  13 iterations: 2683.7
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2699.4
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  12 iterations: 2699.4
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2679.5
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  12 iterations: 2679.5
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2696.6
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  11 iterations: 2696.6
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2685.0
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  12 iterations: 2685.0
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2700.1
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  11 iterations: 2700.1
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2677.8
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  12 iterations: 2677.8
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2694.0
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2678.8
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  12 iterations: 2678.8
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2702.8
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  12 iterations: 2702.8
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2684.1
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  11 iterations: 2684.1
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2699.0
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  12 iterations: 2699.0
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 4158.9
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 2684.4
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  13 iterations: 2684.3
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 7477.7
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after   9 iterations: 4840.6
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: initial function value: 7477.7
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  10 iterations: 4809.8
[GediProgram-1-thread-20] INFO smile.math.Math - L-BFGS: the function value after  12 iterations: 4809.8
2022-04-22 12:38:14.771 INFO Infer ORFs
PRICE
PRICE is an analysis method for Ribo-seq data.

Error:
java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceOrfInference@78280a71
Could not run gedi.riboseq.javapipeline.PriceOrfInference@78280a71
Exception in parallel iterator thread!
/ by zero

gedi -e PRICE <Options>

General:
 -reads <reads>        The mapped reads from the ribo-seq experiment.
 -prefix <prefix>      The prefix used for all output files
 -genomic <genomic>    The indexed GEDI genome.

Commandline:
 -progress             Show progress
 -D                    Verbose output of errors
 -h                    Show usage
 -hh                   Show verbose usage
 -hhh                  Show extra verbose usage
 -dry                  Dry run
 -keep                 Do not remove temp files


java.lang.RuntimeException: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceOrfInference@78280a71
        at gedi.util.job.schedule.DefaultPetriNetScheduler.run(DefaultPetriNetScheduler.java:222)
        at gedi.util.program.GediProgram$1.execute(GediProgram.java:359)
        at gedi.util.program.GediProgram.run(GediProgram.java:204)
        at executables.Price.main(Price.java:68)
Caused by: java.lang.RuntimeException: Could not run gedi.riboseq.javapipeline.PriceOrfInference@78280a71
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:63)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:27)
        at gedi.util.job.FireTransition.call(FireTransition.java:54)
        at gedi.util.job.FireTransition.call(FireTransition.java:25)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Exception in parallel iterator thread!
        at gedi.util.functions.ParallelizedIterator.fatal(ParallelizedIterator.java:221)
        at gedi.util.functions.ParallelizedIterator.tryNext(ParallelizedIterator.java:189)
        at gedi.util.functions.ParallelizedIterator.hasNext(ParallelizedIterator.java:150)
        at java.util.Iterator.forEachRemaining(Iterator.java:115)
        at gedi.riboseq.utils.RiboUtils.lambda$processCodonsSink$4(RiboUtils.java:106)
        at gedi.riboseq.utils.RiboUtils.processCodons(RiboUtils.java:146)
        at gedi.riboseq.utils.RiboUtils.processCodonsSink(RiboUtils.java:106)
        at gedi.riboseq.javapipeline.PriceOrfInference.execute(PriceOrfInference.java:118)
        at gedi.util.program.GediProgramJob.execute(GediProgramJob.java:61)
        ... 7 more
Caused by: java.lang.ArithmeticException: / by zero
        at jdistlib.math.spline.SmoothSpline.formKnots(SmoothSpline.java:155)
        at jdistlib.math.spline.SmoothSpline.fit(SmoothSpline.java:1441)
        at jdistlib.math.spline.SmoothSpline.fitDFMatch(SmoothSpline.java:1296)
        at gedi.riboseq.inference.orf.NoiseModel.computeMeanSpline(NoiseModel.java:188)
        at gedi.riboseq.inference.orf.NoiseModel.getProbability(NoiseModel.java:141)
        at gedi.riboseq.inference.orf.NoiseModel.getProbability0(NoiseModel.java:121)
        at gedi.riboseq.inference.orf.OrfInference.inFrameTestCandidate(OrfInference.java:1271)
        at gedi.riboseq.inference.orf.OrfInference.inFrameTest(OrfInference.java:1079)
        at gedi.riboseq.inference.orf.OrfInference.inferOrfs(OrfInference.java:433)
        at gedi.riboseq.javapipeline.PriceOrfInference.lambda$null$1(PriceOrfInference.java:119)
        at gedi.util.FunctorUtils$DemultiplexIterator.lookAhead(FunctorUtils.java:106)
        at gedi.util.FunctorUtils$DemultiplexIterator.hasNext(FunctorUtils.java:90)
        at gedi.util.FunctorUtils$PeekIterator.hasNext(FunctorUtils.java:636)
        at gedi.util.FunctorUtils$SideEffectIterator.hasNext(FunctorUtils.java:717)
        at gedi.util.functions.ExtendedIterator.toCollection(ExtendedIterator.java:375)
        at gedi.util.functions.ParallelizedIterator$Worker.run(ParallelizedIterator.java:333)
```
Any idea what could cause this error?
Best,
Steven

**Comment by punching-samuel** [comment]
I have met the same problem, have you solved it?

sammi

**Comment by StevenVerbruggen** [comment]
It's been 4 years, so not completely sure, but I think it was related to an uneven coverage of the data. I think there was a problem inferring the ORFs when the coverage is uneven. I think you can check this by inspecting ORFs in the Bedgraphs of the aligned data.
